[package]
name = "spacetime-module"
version = "0.0.6"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "*"
image = { version="*", default-features=false, features=["png", "jpeg"] }
cpal = "0.15.*"
log = "0.4"
