// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_credentials_type::UserCredentials;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `credentials`.
///
/// Obtain a handle from the [`CredentialsTableAccess::credentials`] method on [`super::RemoteTables`],
/// like `ctx.db.credentials()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.credentials().on_insert(...)`.
pub struct CredentialsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserCredentials>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `credentials`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CredentialsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CredentialsTableHandle`], which mediates access to the table `credentials`.
    fn credentials(&self) -> CredentialsTableHandle<'_>;
}

impl CredentialsTableAccess for super::RemoteTables {
    fn credentials(&self) -> CredentialsTableHandle<'_> {
        CredentialsTableHandle {
            imp: self.imp.get_table::<UserCredentials>("credentials"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CredentialsInsertCallbackId(__sdk::CallbackId);
pub struct CredentialsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CredentialsTableHandle<'ctx> {
    type Row = UserCredentials;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserCredentials> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CredentialsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CredentialsInsertCallbackId {
        CredentialsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CredentialsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CredentialsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CredentialsDeleteCallbackId {
        CredentialsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CredentialsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserCredentials>("credentials");
    _table.add_unique_constraint::<u32>("user_id", |row| &row.user_id);
}
pub struct CredentialsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CredentialsTableHandle<'ctx> {
    type UpdateCallbackId = CredentialsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CredentialsUpdateCallbackId {
        CredentialsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CredentialsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserCredentials>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserCredentials>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `user_id` unique index on the table `credentials`,
/// which allows point queries on the field of the same name
/// via the [`CredentialsUserIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.credentials().user_id().find(...)`.
pub struct CredentialsUserIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserCredentials, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CredentialsTableHandle<'ctx> {
    /// Get a handle on the `user_id` unique index on the table `credentials`.
    pub fn user_id(&self) -> CredentialsUserIdUnique<'ctx> {
        CredentialsUserIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("user_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CredentialsUserIdUnique<'ctx> {
    /// Find the subscribed row whose `user_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<UserCredentials> {
        self.imp.find(col_val)
    }
}
