// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EditMessageArgs {
    pub id: u32,
    pub text: String,
}

impl From<EditMessageArgs> for super::Reducer {
    fn from(args: EditMessageArgs) -> Self {
        Self::EditMessage {
            id: args.id,
            text: args.text,
        }
    }
}

impl __sdk::InModule for EditMessageArgs {
    type Module = super::RemoteModule;
}

pub struct EditMessageCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `edit_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait edit_message {
    /// Request that the remote module invoke the reducer `edit_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_edit_message`] callbacks.
    fn edit_message(&self, id: u32, text: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `edit_message`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EditMessageCallbackId`] can be passed to [`Self::remove_on_edit_message`]
    /// to cancel the callback.
    fn on_edit_message(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32, &String) + Send + 'static,
    ) -> EditMessageCallbackId;
    /// Cancel a callback previously registered by [`Self::on_edit_message`],
    /// causing it not to run in the future.
    fn remove_on_edit_message(&self, callback: EditMessageCallbackId);
}

impl edit_message for super::RemoteReducers {
    fn edit_message(&self, id: u32, text: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("edit_message", EditMessageArgs { id, text })
    }
    fn on_edit_message(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32, &String) + Send + 'static,
    ) -> EditMessageCallbackId {
        EditMessageCallbackId(self.imp.on_reducer(
            "edit_message",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EditMessage { id, text },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, text)
            }),
        ))
    }
    fn remove_on_edit_message(&self, callback: EditMessageCallbackId) {
        self.imp.remove_on_reducer("edit_message", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `edit_message`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_edit_message {
    /// Set the call-reducer flags for the reducer `edit_message` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn edit_message(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_edit_message for super::SetReducerFlags {
    fn edit_message(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("edit_message", flags);
    }
}
