// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::linked_user_type::LinkedUser;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `linked`.
///
/// Obtain a handle from the [`LinkedTableAccess::linked`] method on [`super::RemoteTables`],
/// like `ctx.db.linked()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.linked().on_insert(...)`.
pub struct LinkedTableHandle<'ctx> {
    imp: __sdk::TableHandle<LinkedUser>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `linked`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LinkedTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LinkedTableHandle`], which mediates access to the table `linked`.
    fn linked(&self) -> LinkedTableHandle<'_>;
}

impl LinkedTableAccess for super::RemoteTables {
    fn linked(&self) -> LinkedTableHandle<'_> {
        LinkedTableHandle {
            imp: self.imp.get_table::<LinkedUser>("linked"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LinkedInsertCallbackId(__sdk::CallbackId);
pub struct LinkedDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LinkedTableHandle<'ctx> {
    type Row = LinkedUser;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LinkedUser> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LinkedInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinkedInsertCallbackId {
        LinkedInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LinkedInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LinkedDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LinkedDeleteCallbackId {
        LinkedDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LinkedDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LinkedUser>("linked");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<LinkedUser>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LinkedUser>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
