// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::raw_file_type::RawFile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `raw_file`.
///
/// Obtain a handle from the [`RawFileTableAccess::raw_file`] method on [`super::RemoteTables`],
/// like `ctx.db.raw_file()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.raw_file().on_insert(...)`.
pub struct RawFileTableHandle<'ctx> {
    imp: __sdk::TableHandle<RawFile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `raw_file`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RawFileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RawFileTableHandle`], which mediates access to the table `raw_file`.
    fn raw_file(&self) -> RawFileTableHandle<'_>;
}

impl RawFileTableAccess for super::RemoteTables {
    fn raw_file(&self) -> RawFileTableHandle<'_> {
        RawFileTableHandle {
            imp: self.imp.get_table::<RawFile>("raw_file"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RawFileInsertCallbackId(__sdk::CallbackId);
pub struct RawFileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RawFileTableHandle<'ctx> {
    type Row = RawFile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RawFile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RawFileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RawFileInsertCallbackId {
        RawFileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RawFileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RawFileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RawFileDeleteCallbackId {
        RawFileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RawFileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RawFile>("raw_file");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct RawFileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RawFileTableHandle<'ctx> {
    type UpdateCallbackId = RawFileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RawFileUpdateCallbackId {
        RawFileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RawFileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RawFile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RawFile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `raw_file`,
/// which allows point queries on the field of the same name
/// via the [`RawFileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.raw_file().id().find(...)`.
pub struct RawFileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RawFile, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RawFileTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `raw_file`.
    pub fn id(&self) -> RawFileIdUnique<'ctx> {
        RawFileIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RawFileIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<RawFile> {
        self.imp.find(col_val)
    }
}
