// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::file_request_type::FileRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `request`.
///
/// Obtain a handle from the [`RequestTableAccess::request`] method on [`super::RemoteTables`],
/// like `ctx.db.request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.request().on_insert(...)`.
pub struct RequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<FileRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RequestTableHandle`], which mediates access to the table `request`.
    fn request(&self) -> RequestTableHandle<'_>;
}

impl RequestTableAccess for super::RemoteTables {
    fn request(&self) -> RequestTableHandle<'_> {
        RequestTableHandle {
            imp: self.imp.get_table::<FileRequest>("request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RequestInsertCallbackId(__sdk::CallbackId);
pub struct RequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RequestTableHandle<'ctx> {
    type Row = FileRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FileRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequestInsertCallbackId {
        RequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequestDeleteCallbackId {
        RequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FileRequest>("request");
    _table.add_unique_constraint::<__sdk::Identity>("sender", |row| &row.sender);
}
pub struct RequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RequestTableHandle<'ctx> {
    type UpdateCallbackId = RequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RequestUpdateCallbackId {
        RequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FileRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FileRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `sender` unique index on the table `request`,
/// which allows point queries on the field of the same name
/// via the [`RequestSenderUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.request().sender().find(...)`.
pub struct RequestSenderUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FileRequest, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RequestTableHandle<'ctx> {
    /// Get a handle on the `sender` unique index on the table `request`.
    pub fn sender(&self) -> RequestSenderUnique<'ctx> {
        RequestSenderUnique {
            imp: self.imp.get_unique_constraint::<__sdk::Identity>("sender"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RequestSenderUnique<'ctx> {
    /// Find the subscribed row whose `sender` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<FileRequest> {
        self.imp.find(col_val)
    }
}
