// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestFileArgs {
    pub name: String,
    pub size: u64,
}

impl From<RequestFileArgs> for super::Reducer {
    fn from(args: RequestFileArgs) -> Self {
        Self::RequestFile {
            name: args.name,
            size: args.size,
        }
    }
}

impl __sdk::InModule for RequestFileArgs {
    type Module = super::RemoteModule;
}

pub struct RequestFileCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_file {
    /// Request that the remote module invoke the reducer `request_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_request_file`] callbacks.
    fn request_file(&self, name: String, size: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `request_file`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RequestFileCallbackId`] can be passed to [`Self::remove_on_request_file`]
    /// to cancel the callback.
    fn on_request_file(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> RequestFileCallbackId;
    /// Cancel a callback previously registered by [`Self::on_request_file`],
    /// causing it not to run in the future.
    fn remove_on_request_file(&self, callback: RequestFileCallbackId);
}

impl request_file for super::RemoteReducers {
    fn request_file(&self, name: String, size: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("request_file", RequestFileArgs { name, size })
    }
    fn on_request_file(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> RequestFileCallbackId {
        RequestFileCallbackId(self.imp.on_reducer(
            "request_file",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RequestFile { name, size },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, size)
            }),
        ))
    }
    fn remove_on_request_file(&self, callback: RequestFileCallbackId) {
        self.imp.remove_on_reducer("request_file", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `request_file`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_request_file {
    /// Set the call-reducer flags for the reducer `request_file` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn request_file(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_request_file for super::SetReducerFlags {
    fn request_file(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("request_file", flags);
    }
}
