// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestStreamArgs {
    pub name: String,
    pub size: u64,
}

impl From<RequestStreamArgs> for super::Reducer {
    fn from(args: RequestStreamArgs) -> Self {
        Self::RequestStream {
            name: args.name,
            size: args.size,
        }
    }
}

impl __sdk::InModule for RequestStreamArgs {
    type Module = super::RemoteModule;
}

pub struct RequestStreamCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_stream`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_stream {
    /// Request that the remote module invoke the reducer `request_stream` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_request_stream`] callbacks.
    fn request_stream(&self, name: String, size: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `request_stream`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RequestStreamCallbackId`] can be passed to [`Self::remove_on_request_stream`]
    /// to cancel the callback.
    fn on_request_stream(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> RequestStreamCallbackId;
    /// Cancel a callback previously registered by [`Self::on_request_stream`],
    /// causing it not to run in the future.
    fn remove_on_request_stream(&self, callback: RequestStreamCallbackId);
}

impl request_stream for super::RemoteReducers {
    fn request_stream(&self, name: String, size: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("request_stream", RequestStreamArgs { name, size })
    }
    fn on_request_stream(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &u64) + Send + 'static,
    ) -> RequestStreamCallbackId {
        RequestStreamCallbackId(self.imp.on_reducer(
            "request_stream",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RequestStream { name, size },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, size)
            }),
        ))
    }
    fn remove_on_request_stream(&self, callback: RequestStreamCallbackId) {
        self.imp.remove_on_reducer("request_stream", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `request_stream`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_request_stream {
    /// Set the call-reducer flags for the reducer `request_stream` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn request_stream(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_request_stream for super::SetReducerFlags {
    fn request_stream(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("request_stream", flags);
    }
}
