// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendPocketArgs {
    pub pocket: Vec<u8>,
}

impl From<SendPocketArgs> for super::Reducer {
    fn from(args: SendPocketArgs) -> Self {
        Self::SendPocket {
            pocket: args.pocket,
        }
    }
}

impl __sdk::InModule for SendPocketArgs {
    type Module = super::RemoteModule;
}

pub struct SendPocketCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_pocket`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_pocket {
    /// Request that the remote module invoke the reducer `send_pocket` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_pocket`] callbacks.
    fn send_pocket(&self, pocket: Vec<u8>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_pocket`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendPocketCallbackId`] can be passed to [`Self::remove_on_send_pocket`]
    /// to cancel the callback.
    fn on_send_pocket(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SendPocketCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_pocket`],
    /// causing it not to run in the future.
    fn remove_on_send_pocket(&self, callback: SendPocketCallbackId);
}

impl send_pocket for super::RemoteReducers {
    fn send_pocket(&self, pocket: Vec<u8>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("send_pocket", SendPocketArgs { pocket })
    }
    fn on_send_pocket(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SendPocketCallbackId {
        SendPocketCallbackId(self.imp.on_reducer(
            "send_pocket",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SendPocket { pocket },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, pocket)
            }),
        ))
    }
    fn remove_on_send_pocket(&self, callback: SendPocketCallbackId) {
        self.imp.remove_on_reducer("send_pocket", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_pocket`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_pocket {
    /// Set the call-reducer flags for the reducer `send_pocket` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_pocket(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_pocket for super::SetReducerFlags {
    fn send_pocket(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_pocket", flags);
    }
}
