// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendPacketArgs {
    pub pocket: Vec<u8>,
}

impl From<SendPacketArgs> for super::Reducer {
    fn from(args: SendPacketArgs) -> Self {
        Self::SendPacket {
            pocket: args.pocket,
        }
    }
}

impl __sdk::InModule for SendPacketArgs {
    type Module = super::RemoteModule;
}

pub struct SendPacketCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_packet`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_packet {
    /// Request that the remote module invoke the reducer `send_packet` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_packet`] callbacks.
    fn send_packet(&self, pocket: Vec<u8>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_packet`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendPacketCallbackId`] can be passed to [`Self::remove_on_send_packet`]
    /// to cancel the callback.
    fn on_send_packet(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SendPacketCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_packet`],
    /// causing it not to run in the future.
    fn remove_on_send_packet(&self, callback: SendPacketCallbackId);
}

impl send_packet for super::RemoteReducers {
    fn send_packet(&self, pocket: Vec<u8>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("send_packet", SendPacketArgs { pocket })
    }
    fn on_send_packet(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SendPacketCallbackId {
        SendPacketCallbackId(self.imp.on_reducer(
            "send_packet",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SendPacket { pocket },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, pocket)
            }),
        ))
    }
    fn remove_on_send_packet(&self, callback: SendPacketCallbackId) {
        self.imp.remove_on_reducer("send_packet", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_packet`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_packet {
    /// Set the call-reducer flags for the reducer `send_packet` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_packet(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_packet for super::SetReducerFlags {
    fn send_packet(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_packet", flags);
    }
}
