// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAvatarArgs {
    pub data: Vec<u8>,
}

impl From<SetAvatarArgs> for super::Reducer {
    fn from(args: SetAvatarArgs) -> Self {
        Self::SetAvatar { data: args.data }
    }
}

impl __sdk::InModule for SetAvatarArgs {
    type Module = super::RemoteModule;
}

pub struct SetAvatarCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_avatar`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_avatar {
    /// Request that the remote module invoke the reducer `set_avatar` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_avatar`] callbacks.
    fn set_avatar(&self, data: Vec<u8>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_avatar`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetAvatarCallbackId`] can be passed to [`Self::remove_on_set_avatar`]
    /// to cancel the callback.
    fn on_set_avatar(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SetAvatarCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_avatar`],
    /// causing it not to run in the future.
    fn remove_on_set_avatar(&self, callback: SetAvatarCallbackId);
}

impl set_avatar for super::RemoteReducers {
    fn set_avatar(&self, data: Vec<u8>) -> __sdk::Result<()> {
        self.imp.call_reducer("set_avatar", SetAvatarArgs { data })
    }
    fn on_set_avatar(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<u8>) + Send + 'static,
    ) -> SetAvatarCallbackId {
        SetAvatarCallbackId(self.imp.on_reducer(
            "set_avatar",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetAvatar { data },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, data)
            }),
        ))
    }
    fn remove_on_set_avatar(&self, callback: SetAvatarCallbackId) {
        self.imp.remove_on_reducer("set_avatar", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_avatar`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_avatar {
    /// Set the call-reducer flags for the reducer `set_avatar` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_avatar(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_avatar for super::SetReducerFlags {
    fn set_avatar(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_avatar", flags);
    }
}
