// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SignupArgs {
    pub name: String,
    pub password: String,
}

impl From<SignupArgs> for super::Reducer {
    fn from(args: SignupArgs) -> Self {
        Self::Signup {
            name: args.name,
            password: args.password,
        }
    }
}

impl __sdk::InModule for SignupArgs {
    type Module = super::RemoteModule;
}

pub struct SignupCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `signup`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait signup {
    /// Request that the remote module invoke the reducer `signup` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_signup`] callbacks.
    fn signup(&self, name: String, password: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `signup`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SignupCallbackId`] can be passed to [`Self::remove_on_signup`]
    /// to cancel the callback.
    fn on_signup(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> SignupCallbackId;
    /// Cancel a callback previously registered by [`Self::on_signup`],
    /// causing it not to run in the future.
    fn remove_on_signup(&self, callback: SignupCallbackId);
}

impl signup for super::RemoteReducers {
    fn signup(&self, name: String, password: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("signup", SignupArgs { name, password })
    }
    fn on_signup(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> SignupCallbackId {
        SignupCallbackId(self.imp.on_reducer(
            "signup",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Signup { name, password },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, password)
            }),
        ))
    }
    fn remove_on_signup(&self, callback: SignupCallbackId) {
        self.imp.remove_on_reducer("signup", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `signup`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_signup {
    /// Set the call-reducer flags for the reducer `signup` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn signup(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_signup for super::SetReducerFlags {
    fn signup(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("signup", flags);
    }
}
