// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::temp_file_type::TempFile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `temp_file`.
///
/// Obtain a handle from the [`TempFileTableAccess::temp_file`] method on [`super::RemoteTables`],
/// like `ctx.db.temp_file()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.temp_file().on_insert(...)`.
pub struct TempFileTableHandle<'ctx> {
    imp: __sdk::TableHandle<TempFile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `temp_file`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TempFileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TempFileTableHandle`], which mediates access to the table `temp_file`.
    fn temp_file(&self) -> TempFileTableHandle<'_>;
}

impl TempFileTableAccess for super::RemoteTables {
    fn temp_file(&self) -> TempFileTableHandle<'_> {
        TempFileTableHandle {
            imp: self.imp.get_table::<TempFile>("temp_file"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TempFileInsertCallbackId(__sdk::CallbackId);
pub struct TempFileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TempFileTableHandle<'ctx> {
    type Row = TempFile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TempFile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TempFileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TempFileInsertCallbackId {
        TempFileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TempFileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TempFileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TempFileDeleteCallbackId {
        TempFileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TempFileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TempFile>("temp_file");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}
pub struct TempFileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TempFileTableHandle<'ctx> {
    type UpdateCallbackId = TempFileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TempFileUpdateCallbackId {
        TempFileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TempFileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TempFile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TempFile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `temp_file`,
/// which allows point queries on the field of the same name
/// via the [`TempFileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.temp_file().id().find(...)`.
pub struct TempFileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TempFile, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TempFileTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `temp_file`.
    pub fn id(&self) -> TempFileIdUnique<'ctx> {
        TempFileIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TempFileIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<TempFile> {
        self.imp.find(col_val)
    }
}
