// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::view_access_type::ViewAccess;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `view`.
///
/// Obtain a handle from the [`ViewTableAccess::view`] method on [`super::RemoteTables`],
/// like `ctx.db.view()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.view().on_insert(...)`.
pub struct ViewTableHandle<'ctx> {
    imp: __sdk::TableHandle<ViewAccess>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `view`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ViewTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ViewTableHandle`], which mediates access to the table `view`.
    fn view(&self) -> ViewTableHandle<'_>;
}

impl ViewTableAccess for super::RemoteTables {
    fn view(&self) -> ViewTableHandle<'_> {
        ViewTableHandle {
            imp: self.imp.get_table::<ViewAccess>("view"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ViewInsertCallbackId(__sdk::CallbackId);
pub struct ViewDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ViewTableHandle<'ctx> {
    type Row = ViewAccess;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ViewAccess> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ViewInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ViewInsertCallbackId {
        ViewInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ViewInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ViewDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ViewDeleteCallbackId {
        ViewDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ViewDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ViewAccess>("view");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ViewAccess>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ViewAccess>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
