// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::voice_packet_type::VoicePacket;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `voice_packet`.
///
/// Obtain a handle from the [`VoicePacketTableAccess::voice_packet`] method on [`super::RemoteTables`],
/// like `ctx.db.voice_packet()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.voice_packet().on_insert(...)`.
pub struct VoicePacketTableHandle<'ctx> {
    imp: __sdk::TableHandle<VoicePacket>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `voice_packet`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VoicePacketTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VoicePacketTableHandle`], which mediates access to the table `voice_packet`.
    fn voice_packet(&self) -> VoicePacketTableHandle<'_>;
}

impl VoicePacketTableAccess for super::RemoteTables {
    fn voice_packet(&self) -> VoicePacketTableHandle<'_> {
        VoicePacketTableHandle {
            imp: self.imp.get_table::<VoicePacket>("voice_packet"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VoicePacketInsertCallbackId(__sdk::CallbackId);
pub struct VoicePacketDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VoicePacketTableHandle<'ctx> {
    type Row = VoicePacket;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VoicePacket> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VoicePacketInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoicePacketInsertCallbackId {
        VoicePacketInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VoicePacketInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VoicePacketDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VoicePacketDeleteCallbackId {
        VoicePacketDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VoicePacketDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VoicePacket>("voice_packet");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VoicePacket>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VoicePacket>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
